dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide
branches:
  only: master

stages:
- build
- name: deploy
  if: (NOT type IN (pull_request)) AND (branch = master)

# One job per project in the monorepo, denoted by the JOB environment variable
jobs:
  include:
  - env: JOB=yfuzz-server
    stage: build
    language: go
  - env: JOB=yfuzz-cli
    stage: build
    language: go
  - env: JOB=yfuzz-scripts
    stage: build
    services:
    - docker
  - env:
    - JOB=deploy-github
    - secure: "A7D0i9di6x81kLiO4jFWDAItRXtvkbYCu0r6cDiOSvxNy5Pqjf7an8d2xaro5SFIaWxijVJe7FWkqvdDB6X/vxCdEAuwcA1k1VoR3G6QC63uDraixG3B9CjR+dEYp8WE9wNFYmKubbpITtO16VyDNjOgIIEgjuW5AjTcQ7NdVTPRrsu7lIVDi4gL/33kj/fMCGQN1XuJ6/3P3UrR3A+044mlpjxU9B1MRoQfPVYaBgwkggZg4YkkYCsyzKW/H34ZqHAhQ+1p+P1xEJN5SeFsRLpT0A+fcEvLTv1EsyUMZIZze/EdXY87rmGf1oWh5J+skd4JADGs2YUFOyqSEUJ1Btwe1k3sco/MTXVFNbX7OaaW2E7cTQ+KPKagapeIRzTaKoc5hsv4hbLWlD0aE3s6r0iWNwpIH7xxoWoZHyzQ5ABvCc0seYO0p+xNhZF7vYrXf2kqchz3BrFJzZ74kwJQ47OpBqRwuNLEpM+gNwNVOiKS39QaYJc+KK81TVHLbCPF3lpT86T9UwfzwGQMOSnTaGxk6T+MddDttQydEsoHTkmX1ZpeGBHmeR9oj9V9km1GNOH1xiir9sY0Uq2jwELeymebZO7blPgycMxXx08bTPL40CV8gMgNO9uoEAjRG5k8A3XY0gfIHAaBPQ3wYtd2n3HntesiYdLF8yK1ICT9aMs="
    stage: deploy
  - env:
    - JOB=deploy-dockerhub
    - secure: "Rkl2aVRnReMQnwHwOR79n9T33HbOirnmLNEuRvdz6SYd9IqX1sW2Giy/wNEoPOeekZC18H4ue/+LaS/08ICF0GQNg/JCR4Hmr8AJapLspYmDekPTy337MYM+qdYures8YjXU3d+32ooAmRW+a3PHjNm8aHX++lXNs+FUTmJEvUqy5fD/OtdvEGxttmVwFwnT5S7ZAnOe7kYMzB7KCLmeL0+VlNaWGY8kjgWa2T0Su0VwGaCV1bazBCh3d2R6rjl+0NdCIJYuafQ00KfIWAjgL4wyCs/eWtuuHUfVWj9jwDBmg+oTaG/oPQ69XWD0qw/FSn9qjuYO4yM0Qh2hyAKj8pWZo1ICyi+JIkxySHRmDKXycJM6cMOOh8uBgdftgGGAbjiDpk7p1eFptk2hQ+A21tkVgs1s7fl0oW8wImZNhFkgoleaTzfALT5vL6b3rxYjXBvRrVzThRE1RK76leiZ0aGUZYWPCQgHu0xDGwVnUP38iH7Ks5HYpPj5h8Hb9+WdykTpGTkTyDmwF70iVHgEPiBDU08pcGwG6dq9Qtugc+l28vOgB+1UNEnprOQlrRFfwGq+iFpLoWlywx3zYqT6qW2Ke/7o/3CJey0Bk8/QCxUs6brqb6GBT06Fn50HW6Eb07PvpFd45ROoAxKhxcotUSErXa6F7ge+mctqnlA30+c="
    stage: deploy
    services:
    - docker

# Make will handle the actual building
script:
- source ./scripts/git_version.sh
- make subproject target=$JOB verbose=true
