# Information for kubernetes and job configuration
kubernetes:
  # Config for yFuzz jobs
  job-config:
    # Number of concurrent pods to run per job
    parallelism: 3

    # PVC for sharing corpora
    persistent-volume-claim: yfuzz-volume

    # Configuration for the logging sidecar
    log:
      # yFuzz will tail the log of a pod and look for a specified string to indicate success
      crash-found-message: SUCCESS
      tail-lines: 5

    # Memory/CPU limits for pods
    memory:
      request: 100Mi
      limit: 1Gi
    cpu:
      request: 0.5
      limit: 1
